sudo: required
language: python
install: true
script: wget -O- https://raw.githubusercontent.com/dream-alpha/pybake/master/src/pybake.py | python - -i . -o $HOME
before_deploy: git tag 1.8.13
deploy:
  provider: releases
  api_key:
    secure: NtODekVo4BeqPTKS4R7JOE68HoU7GcKihiwTI1ao4knA5hMArELNbIcZL5tFk6/EeOntWpdrTrbVvgPw92LhL4KNcdtTo3RM5Twew7eSEEsjh8VfwMBupzXUfUH+PfVpmKmE5bpS0ABEDZBbppaZ2mgPiNViXKX5O9agEgwBQzzZwAW0atjUidbX+UTD1eqSDOc7gaALsrV2SbBpSwEpaM7KLasbeBeH/ZwFP9d1FI+PJIvzEqOKjcMby4LIYu31zDLUnt9MzfprL/C0Yad9OG2Jc3G03HrJlIQHVwdolrp2KDg4b7AN5rTDrt8D7wANOrjHyJ97XMgf/JP9WrnjQgb13Y8S/6+jMAXM3/dYY9BL1t9GkUgoK0IiYmRYyoWMVLbzfvoWlKjs87FWxlLvwnkLWMFxAJWY/WYh6aZjpNQ5mslFAke98iFLEckFFP3HEOVm9H99BE8VRC0PsXke6ww8T1/t26GJTBFtLj1ZfMdiJi6B7VUE5E/VtdDR6R+VWR9i/DmjGPaWg+3+dk7SU0gOdoQX4neOop04N/GR05jbZfya0yZqDeVrA0rS7ecXGQR5ZnY7HWV8WdguhV9CKAojKxD+BuzyAKN8/KRmnd53zGcrCYZ3oAwYKnXuY3Uz2l3JxuWYo8MSi4pfJ4bbtOtn6ze7R2x0E2bTK9rUuzQ=
  file_glob: true
  file: "$HOME/enigma2-plugin*"
  on:
    repo: dream-alpha/MovieCockpit
